### PR TITLE
add a notebook about periods.

### PR DESCRIPTION
**Pull request by adrienpacifico**
Many flows are present (English, formating, etc), might not work with last version of OpenFisca.

### CODE REVIEW

**Comment by laem** [comment]
That's highly needed !

**Comment by edarin** [comment]
Wouldn't it be better to have this notebook in this repo : https://github.com/openfisca/openfisca-france/tree/master/notebooks ?

Else : how can we see it before the merge ? (i mean the commit just show the script behind the notebook ...)

**Comment by adrienpacifico** [comment]
To display it you can look at the repo from which I did my pull request : https://github.com/adrienpacifico/openfisca-web-notebook/blob/master/documentation/how-period-works(WIP).ipynb

For the repo I don't know, feel free to place it where you think it should be !

**Comment by Morendil** [comment]
This seems to be in tutorial now.

**Pull request closed without merging**
